-- Customer Readiness Checklist tables
-- Run this in the Supabase SQL editor.
-- Assumes is_admin() helper already exists (from sharing.sql or machines.sql).

-- 1. Templates: admin-managed sets of checklist items
create table if not exists public.falu_checklist_templates (
  id         uuid        primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  created_by uuid        references auth.users(id) on delete set null,
  name       text        not null,
  items      jsonb       not null default '[]'::jsonb
  -- items: [{id: string, label: string, required: boolean}]
);
alter table public.falu_checklist_templates enable row level security;
create policy "auth read templates"   on public.falu_checklist_templates for select using (auth.role() = 'authenticated');
create policy "admin insert templates" on public.falu_checklist_templates for insert with check (is_admin());
create policy "admin update templates" on public.falu_checklist_templates for update using (is_admin());
create policy "admin delete templates" on public.falu_checklist_templates for delete using (is_admin());

-- 2. Checklists: instances sent to customers
create table if not exists public.falu_checklists (
  id             uuid        primary key default gen_random_uuid(),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  created_by     uuid        references auth.users(id) on delete set null,
  template_id    uuid        references public.falu_checklist_templates(id) on delete set null,
  customer_name  text,
  site           text,
  scheduled_date date,
  items          jsonb       not null default '[]'::jsonb,
  -- items: [{id, label, required, checked, note, media: [storagePath]}]
  status         text        not null default 'pending' check (status in ('pending','submitted')),
  customer_token uuid        not null default gen_random_uuid()
);
alter table public.falu_checklists enable row level security;
-- Staff (any authenticated user) can read and write all checklists.
-- Customer access goes through the edge function using the service role key.
create policy "auth manage checklists" on public.falu_checklists for all using (auth.role() = 'authenticated');

-- 3. Storage bucket for customer-uploaded media (photos & videos)
insert into storage.buckets (id, name, public)
  values ('falu-checklist-media', 'falu-checklist-media', false)
  on conflict (id) do nothing;

-- Staff can read media via signed URLs generated by the app.
-- Customer uploads go through the edge function (service role bypasses RLS).
create policy "auth read checklist media" on storage.objects for select
  using (bucket_id = 'falu-checklist-media' and auth.role() = 'authenticated');
